GET https://localhost:5001/api/lobbyGames
###
GET https://localhost:5001/api/lobbyGames/getLobbyGameById/1
###
POST localhost:5001/api/lobbyGames/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjpbIlBsYXllciIsIkFkbWluIl0sInVuaXF1ZV9uYW1lIjoic3VwcGVyMjQiLCJuYmYiOjE2MTU4MTg1NTcsImV4cCI6MTYxNTgyMDM1NywiaWF0IjoxNjE1ODE4NTU3fQ.cqk9pLmvADxLcUi9o0H4OD36DSEZxKsz9MhEOF4yHVQ
Content-Type: application/json

{
    "Date":"2021-01-18T20:00:00",
    "ModeId":1
}
###
PUT localhost:5001/api/lobbyGames/
Content-Type: application/json

{
    "Id":1,
    "Date":"2020-08-13T12:00:00",
    "ModeId":2
}
###
DELETE https://localhost:5001/api/lobbyGames/2

